//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 



namespace MusicXML
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class print
    {

        private pagelayout pagelayoutField;

        private systemlayout systemlayoutField;

        private stafflayout[] stafflayoutField;

        private measurelayout measurelayoutField;

        private measurenumbering measurenumberingField;

        private namedisplay partnamedisplayField;

        private namedisplay partabbreviationdisplayField;

        private decimal staffspacingField;

        private bool staffspacingFieldSpecified;

        private yesno newsystemField;

        private bool newsystemFieldSpecified;

        private yesno newpageField;

        private bool newpageFieldSpecified;

        private string blankpageField;

        private string pagenumberField;


        [System.Xml.Serialization.XmlElementAttribute("page-layout")]
        public pagelayout pagelayout
        {
            get
            {
                return this.pagelayoutField;
            }
            set
            {
                this.pagelayoutField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute("system-layout")]
        public systemlayout systemlayout
        {
            get
            {
                return this.systemlayoutField;
            }
            set
            {
                this.systemlayoutField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute("staff-layout")]
        public stafflayout[] stafflayout
        {
            get
            {
                return this.stafflayoutField;
            }
            set
            {
                this.stafflayoutField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute("measure-layout")]
        public measurelayout measurelayout
        {
            get
            {
                return this.measurelayoutField;
            }
            set
            {
                this.measurelayoutField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute("measure-numbering")]
        public measurenumbering measurenumbering
        {
            get
            {
                return this.measurenumberingField;
            }
            set
            {
                this.measurenumberingField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute("part-name-display")]
        public namedisplay partnamedisplay
        {
            get
            {
                return this.partnamedisplayField;
            }
            set
            {
                this.partnamedisplayField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute("part-abbreviation-display")]
        public namedisplay partabbreviationdisplay
        {
            get
            {
                return this.partabbreviationdisplayField;
            }
            set
            {
                this.partabbreviationdisplayField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("staff-spacing")]
        public decimal staffspacing
        {
            get
            {
                return this.staffspacingField;
            }
            set
            {
                this.staffspacingField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool staffspacingSpecified
        {
            get
            {
                return this.staffspacingFieldSpecified;
            }
            set
            {
                this.staffspacingFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("new-system")]
        public yesno newsystem
        {
            get
            {
                return this.newsystemField;
            }
            set
            {
                this.newsystemField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newsystemSpecified
        {
            get
            {
                return this.newsystemFieldSpecified;
            }
            set
            {
                this.newsystemFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("new-page")]
        public yesno newpage
        {
            get
            {
                return this.newpageField;
            }
            set
            {
                this.newpageField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool newpageSpecified
        {
            get
            {
                return this.newpageFieldSpecified;
            }
            set
            {
                this.newpageFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("blank-page", DataType = "positiveInteger")]
        public string blankpage
        {
            get
            {
                return this.blankpageField;
            }
            set
            {
                this.blankpageField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("page-number", DataType = "token")]
        public string pagenumber
        {
            get
            {
                return this.pagenumberField;
            }
            set
            {
                this.pagenumberField = value;
            }
        }
    }
}